### PR TITLE
Fix update_role and add tests

### PR DESCRIPTION
**Pull request by JayDwee**
fix update_role and add tests
Add Issue templates and dependabot.yml

Update .travis.yml
Add python 3.9 to travis tests

The bot tag is given to the FakeApp ClientUser

(Correct Branch from #12 )

### CODE REVIEW

**Comment by bravosierra99** [comment]
Ok haha. I have a partial review that mostly says "erm did you mean to commit this?"

Fixing up my docker install so I can make sure your code runs ok with my bot and tests.

**Comment by bravosierra99** [comment]
So I actually still want to confirm, there seem to be a bunch of things you were adding that seem to be for your bot?  templates that seem specific to your bot, an updated .gitignore (could go either way), removing requirements.txt(??)

I don't see anything wrong with your actual edits, it wasn't an issue that I came across but I'll believe it was an issue since I come across things like this all the time.  Anyways, I'm tracking backend.py, state.py and test_role.py as all making sense to me.  Can you confirm the rest of the changes?

**Comment by JayDwee** [comment]
So I added requirements.txt but realised that I should be using dev-requirements.txt so removed it again later
.gitignore change allows developers to use virtual environments (including me)

As for templates I believe I have removed all specifics for Koala, only other thing that can be removed if you want is the contact details section on the bug report. I added that as most of the people finding bugs may not use GitHub enough to respond through it, but I guess on this repo everyone accessing it would be active anyway.

**Comment by bravosierra99** [comment]
thanks for responding!  I think that helps.  I'll go ahead and accept... and we'll see what the upstream does with some of the new things.

**Review by bravosierra99 — APPROVED** [review]

**Pull request merged**
